import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WholeAppProvider } from "@/components/AuthContextAPI";
import AuthGuard from "@/components/AuthGuard";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MITS INTERNPORT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="">
<WholeAppProvider>
     <Toaster richColors position="top-center" />
<AuthGuard />
        {children}
        
</WholeAppProvider>
        </main>
      </body>
    </html>
  );
}
